#############################################################################
# Makefile for building: libthetastar.1.0.0.dylib
# Generated by qmake (3.0) (Qt 5.0.2) on: Sat Aug 17 12:01:14 2013
# Project:  thetastar.pro
# Template: lib
# Command: /Applications/Qt5.0.2/5.0.2/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile thetastar.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DTHETASTAR_LIBRARY -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -mmacosx-version-min=10.6 -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -mmacosx-version-min=10.6 -O2 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/macx-clang -I. -I. -I/Applications/Qt5.0.2/5.0.2/clang_64/include -I/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore -I/Applications/Qt5.0.2/5.0.2/clang_64/lib/QtCore.framework/Versions/5/Headers -Ibin/tmp/moc
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -mmacosx-version-min=10.6 -single_module -dynamiclib -compatibility_version	1.0 -current_version	1.0.0 -install_name	libthetastar.1.dylib
LIBS          = $(SUBLIBS) -F/Applications/Qt5.0.2/5.0.2/clang_64/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Applications/Qt5.0.2/5.0.2/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = bin/tmp/obj/

####### Files

SOURCES       = lib/map.cpp \
		lib/planner.cpp \
		lib/vertex.cpp bin/tmp/moc/moc_map.cpp \
		bin/tmp/moc/moc_planner.cpp
OBJECTS       = bin/tmp/obj/map.o \
		bin/tmp/obj/planner.o \
		bin/tmp/obj/vertex.o \
		bin/tmp/obj/moc_map.o \
		bin/tmp/obj/moc_planner.o
DIST          = /Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base-macx.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac-minimum-version.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/default_pre.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/lex.prf \
		thetastar.pro \
		thetastar.pro
QMAKE_TARGET  = thetastar
DESTDIR       = bin/release/
TARGET        = libthetastar.1.0.0.dylib
TARGETA       = bin/release/libthetastar.a
TARGETD       = libthetastar.1.0.0.dylib
TARGET0       = libthetastar.dylib
TARGET1       = libthetastar.1.dylib
TARGET2       = libthetastar.1.0.dylib

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-mmacosx-version-min=10.6 \
		-O2 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  bin/release/$(TARGET)

bin/release/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d bin/release/ || mkdir -p bin/release/
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) bin/release/$(TARGET)
	-$(DEL_FILE) bin/release/$(TARGET0)
	-$(DEL_FILE) bin/release/$(TARGET1)
	-$(DEL_FILE) bin/release/$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) bin/release/



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)
	$(RANLIB) $(TARGETA)

Makefile: thetastar.pro /Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base-macx.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac-minimum-version.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/default_pre.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/lex.prf \
		thetastar.pro \
		/Applications/Qt5.0.2/5.0.2/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile thetastar.pro
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/qdevice.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/shell-unix.conf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/unix.conf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac.conf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/gcc-base-macx.conf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang.conf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/common/mac-minimum-version.conf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/qconfig.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_bootstrap.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_clucene.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_v8.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/spec_post.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/default_pre.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/qt.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/resources.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/moc.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt5.0.2/5.0.2/clang_64/mkspecs/features/lex.prf:
thetastar.pro:
/Applications/Qt5.0.2/5.0.2/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile thetastar.pro

qmake_all: FORCE

dist: 
	@test -d bin/tmp/obj/thetastar1.0.0 || mkdir -p bin/tmp/obj/thetastar1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) bin/tmp/obj/thetastar1.0.0/ && $(COPY_FILE) --parents include/coordinate.h include/global.h include/map.h include/planner.h include/vertex.h bin/tmp/obj/thetastar1.0.0/ && $(COPY_FILE) --parents lib/map.cpp lib/planner.cpp lib/vertex.cpp bin/tmp/obj/thetastar1.0.0/ && (cd `dirname bin/tmp/obj/thetastar1.0.0` && $(TAR) thetastar1.0.0.tar thetastar1.0.0 && $(COMPRESS) thetastar1.0.0.tar) && $(MOVE) `dirname bin/tmp/obj/thetastar1.0.0`/thetastar1.0.0.tar.gz . && $(DEL_FILE) -r bin/tmp/obj/thetastar1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) bin/release/$(TARGET) 
	-$(DEL_FILE) bin/release/$(TARGET0) bin/release/$(TARGET1) bin/release/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: bin/tmp/moc/moc_map.cpp bin/tmp/moc/moc_planner.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) bin/tmp/moc/moc_map.cpp bin/tmp/moc/moc_planner.cpp
bin/tmp/moc/moc_map.cpp: /Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/QMap \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qmap.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qflags.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlist.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qpair.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qdebug.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qhash.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qchar.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtextstream.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qiodevice.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qstring.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject_impl.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlocale.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvariant.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qshareddata.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvector.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qpoint.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qset.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcontiguouscache.h \
		include/vertex.h \
		include/coordinate.h \
		include/global.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/QObject \
		include/map.h
	/Applications/Qt5.0.2/5.0.2/clang_64/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 include/map.h -o bin/tmp/moc/moc_map.cpp

bin/tmp/moc/moc_planner.cpp: include/map.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/QMap \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qmap.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qflags.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlist.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qpair.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qdebug.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qhash.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qchar.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtextstream.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qiodevice.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qstring.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject_impl.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlocale.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvariant.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qshareddata.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvector.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qpoint.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qset.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcontiguouscache.h \
		include/vertex.h \
		include/coordinate.h \
		include/global.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/QObject \
		include/planner.h
	/Applications/Qt5.0.2/5.0.2/clang_64/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 include/planner.h -o bin/tmp/moc/moc_planner.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

bin/tmp/obj/map.o: lib/map.cpp include/map.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/QMap \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qmap.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qflags.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlist.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qpair.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qdebug.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qhash.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qchar.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtextstream.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qiodevice.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qstring.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject_impl.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlocale.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvariant.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qshareddata.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvector.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qpoint.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qset.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcontiguouscache.h \
		include/vertex.h \
		include/coordinate.h \
		include/global.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/QObject
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/tmp/obj/map.o lib/map.cpp

bin/tmp/obj/planner.o: lib/planner.cpp include/planner.h \
		include/map.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/QMap \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qmap.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qflags.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlist.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qpair.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qdebug.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qhash.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qchar.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtextstream.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qiodevice.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qstring.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject_impl.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlocale.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvariant.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qshareddata.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvector.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qpoint.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qset.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcontiguouscache.h \
		include/vertex.h \
		include/coordinate.h \
		include/global.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/QObject
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/tmp/obj/planner.o lib/planner.cpp

bin/tmp/obj/vertex.o: lib/vertex.cpp include/vertex.h \
		include/coordinate.h \
		include/global.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/QObject \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qflags.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qstring.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qchar.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qlist.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt5.0.2/5.0.2/clang_64/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/tmp/obj/vertex.o lib/vertex.cpp

bin/tmp/obj/moc_map.o: bin/tmp/moc/moc_map.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/tmp/obj/moc_map.o bin/tmp/moc/moc_map.cpp

bin/tmp/obj/moc_planner.o: bin/tmp/moc/moc_planner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/tmp/obj/moc_planner.o bin/tmp/moc/moc_planner.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(INSTALL_PROGRAM) "bin/release/$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET0)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET1)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET2)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET0)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET1)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET2)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

